version: '3.8'
services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db-sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9003:9000"
    networks:
      - sonartest
  db-sonarqube:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonartest

networks:
  sonartest:
    driver: bridge

volumes:
  pgsql:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
